version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  write-api:
    build: 
     context: .
     dockerfile: Dockerfile.write
    container_name: write-weather-api
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - PORT=4000

  read-api:
    build: 
     context: .
     dockerfile: Dockerfile.read
    container_name: read-weather-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - PORT=5000

volumes:
  mongodb_data:
